#!/bin/sh

. /Applications/drupal-7.41-1/scripts/setenv.sh

exec /Applications/drupal-7.41-1/php/sbin/.php-fpm.bin -y /Applications/drupal-7.41-1/php/etc/php-fpm.conf -p /Applications/drupal-7.41-1/php/var/ -c /Applications/drupal-7.41-1/php/etc/php.ini "$@"
