#!/bin/sh

. /Applications/drupal-7.41-1/scripts/setenv.sh
SASL_PATH="/Applications/drupal-7.41-1/common/lib/sasl2"
                export SASL_PATH
exec /Applications/drupal-7.41-1/common/sbin/.sasldblistusers2.bin -f "/Applications/drupal-7.41-1/common/etc/sasldb2" "$@"
